### ISSUE TITLE
This happened when I tried to look at the Freezer's description

### ISSUE THREAD

**Issue by Arthur-The-Ok** [3Snake3/Sapphirium#5]
rhino.EcmaError: ReferenceError: "NumberValue" is not defined. (multi-lib#594)
	at rhino.ScriptRuntime.constructError(ScriptRuntime.java:3720)
	at rhino.ScriptRuntime.constructError(ScriptRuntime.java:3700)
	at rhino.ScriptRuntime.notFoundError(ScriptRuntime.java:3777)
	at rhino.ScriptRuntime.nameOrFunction(ScriptRuntime.java:1702)
	at rhino.ScriptRuntime.name(ScriptRuntime.java:1656)
	at rhino.gen.multi_lib_5._c_anonymous_63(multi-lib:594)
	at rhino.gen.multi_lib_5.call(multi-lib)
	at rhino.ArrowFunction.call(ArrowFunction.java:33)
	at rhino.JavaAdapter.doCall(JavaAdapter.java:492)
	at rhino.JavaAdapter.callMethod(JavaAdapter.java:474)
	at adapter18.get(<adapter>)
	at arc.scene.ui.layout.Table.table(Table.java:264)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at rhino.MemberBox.invoke(MemberBox.java:104)
	at rhino.NativeJavaMethod.call(NativeJavaMethod.java:205)
	at rhino.optimizer.OptRuntime.call1(OptRuntime.java:23)
	at rhino.gen.multi_lib_5._c_anonymous_60(multi-lib:595)
	at rhino.gen.multi_lib_5.call(multi-lib)
	at rhino.ArrowFunction.call(ArrowFunction.java:33)
	at rhino.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:141)
	at rhino.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:92)
	at rhino.Context.call(Context.java:450)
	at rhino.ContextFactory.call(ContextFactory.java:428)
	at rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:92)
	at rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:142)
	at jdk.proxy1/jdk.proxy1.$Proxy2.get(Unknown Source)
	at arc.scene.ui.layout.Table.table(Table.java:275)
	at arc.scene.ui.layout.Table.table(Table.java:269)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at rhino.MemberBox.invoke(MemberBox.java:104)
	at rhino.NativeJavaMethod.call(NativeJavaMethod.java:205)
	at rhino.optimizer.OptRuntime.call2(OptRuntime.java:32)
	at rhino.gen.multi_lib_5._c_anonymous_59(multi-lib:615)
	at rhino.gen.multi_lib_5.call(multi-lib)
	at rhino.ContextFactory.doTopCall(ContextFactory.java:328)
	at rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:3093)
	at rhino.gen.multi_lib_5.call(multi-lib)
	at rhino.ArrowFunction.call(ArrowFunction.java:33)
	at rhino.JavaAdapter.doCall(JavaAdapter.java:492)
	at rhino.JavaAdapter.callMethod(JavaAdapter.java:474)
	at adapter109.display(<adapter>)
	at mindustry.ui.dialogs.ContentInfoDialog.lambda$show$1(ContentInfoDialog.java:73)
	at arc.scene.ui.layout.Table.table(Table.java:264)
	at mindustry.ui.dialogs.ContentInfoDialog.show(ContentInfoDialog.java:68)
	at mindustry.ui.fragments.PlacementFragment.lambda$build$14(PlacementFragment.java:318)
	at arc.scene.Element$9.changed(Element.java:964)
	at arc.scene.event.ChangeListener.handle(ChangeListener.java:13)
	at arc.scene.Element.notify(Element.java:162)
	at arc.scene.Element.fire(Element.java:133)
	at arc.scene.ui.Button.setChecked(Button.java:106)
	at arc.scene.ui.Button$1.clicked(Button.java:92)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:31)
	at arc.scene.Scene.touchUp(Scene.java:365)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:137)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:102)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:150)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:38)

**Comment by 3Snake3** [comment]
@Arthur-The-Ok I fixed the Multi Crafter, now it works correctly. I will release update soon.
